apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cakemanager
  name: cakemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cakemanager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cakemanager
    spec:
      containers:
      - image: aws2411/cakemanager
        name: cakemanager
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cakemanager
  name: cakemanager
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cakemanager
  type: ClusterIP
status:
  loadBalancer: {}
